# Generated by Django 3.1.6 on 2021-04-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app_1', '0003_auto_20210305_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='main_data',
            field=models.JSONField(null=True),
        ),
    ]
