# Generated by Django 3.1.6 on 2021-04-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app_1', '0004_auto_20210419_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=38, primary_key=True, serialize=False, unique=True),
        ),
    ]
