# Generated by Django 3.1.6 on 2021-04-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app_1', '0006_localsettings_recordtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordType',
            new_name='LocalRecordType',
        ),
    ]
